### PR TITLE
Various Features

### PR DESCRIPTION
**Pull request by artyredd**
- Added the ability to toggle on/off the "pickupable" status of all animation camera lenses
- Added the ability to toggle on/off position, rotation, zoom key frames
- Added zoom (Lens Shift, Sensor Size, and Focal Length) keying
- Refactored `StoredTransform` to allow for adding more keying
- Added serialization for added keying and modified existing keying
- Added ability to change key frame length (minimums and maximums) during runtime (this is separate from animation speed, which is unchanged)

Notes:
- No Icons were added to the added GUI features
- Zoom keying can be weird on very low end hardware (AKA integrated GPU). I've found when Zoom keying is enabled and VRC is running at 15-30FPS stuttering can occur in the animation. This cannot be replicated on higher hardware. This feature may want to be disabled by default until I/we can figure out why it's stuttering.

### CODE REVIEW

**Comment by Er1807** [comment]
ok holy shit thats a lot. gonna check it out today

**Comment by Er1807** [comment]
@DekuDesu I checked it out and it seems to work, but do Lens Shift and Sensor Size ever change? 
Doesnt matter what i did they were always at
Camera.lensShift = 0 0
Camera.sensorSize = 70 51

**Comment by artyredd** [comment]
Great question! They did for me, but in unexpected and unreproducible ways! Likely some VRC spaghetti, but I erred on the side of caution and included them as well. Should vrc implement something that uses them (in an expected way) it will be automatically supported. 

One thing I did not test was the 'focus' feature on the camera, not sure if that affects those members at all.

**Comment by Er1807** [comment]
One thing I did not test was the 'focus' feature on the camera, not sure if that affects those members at all.
Tested it a bit and it seems no. I couldnt find at all which params they changed or if thats all in some kind of shader. gonna look at it later

**Comment by Er1807** [comment]
Found the class that stores them and is used during rendering
MonoBehaviourPublicAcInCaInTeShInMaBoInUnique
field_Public_Single_7 =  target focal distance, field_Public_Single_2  = currrent focal distance
field_Public_Single_9 = target apature,  field_Public_Single_4= current apature

But these names need to be checked at runtime since the order can scrampble between diffrent vrc builds

I can create some code to automatically find the field names in a bit

And I only think it will work in manuell mode properly

**Comment by Er1807** [comment]
time to merge my changes into it. Added some stuff in the meantime.

**Comment by Er1807** [comment]
Feel free to message me on discord 
Eric van Fandenfart#1807

**Comment by artyredd** [comment]
rip

**Pull request merged**
